version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: case_study_db
    environment:
      MYSQL_DATABASE: routes_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: vLUWqsSB
      MYSQL_PASSWORD: mvUkveLN
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis-cache:
    image: redis:7-alpine
    container_name: case_study_redis
    ports:
      - "6379:6379"

  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: case_study_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/routes_db?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=vLUWqsSB
      - SPRING_DATASOURCE_PASSWORD=mvUkveLN
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-cache:
        condition: service_started

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: case_study_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend-app
