version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: routes-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: AWsWFMYz
      MYSQL_DATABASE: routes_db        # Auto-creates this database on startup
      MYSQL_USER: vLUWqsSB             # Auto-creates this user
      MYSQL_PASSWORD: mvUkveLN     # Grants the user access to the database
    ports:
      - "3306:3306"
    command: >
      --skip-ssl 
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql      # The magic line that saves your data!

# Defines the physical storage space on your hard drive
volumes:
  mysql_data: